/*************************************************************************
 * ADOBE CONFIDENTIAL
 * ___________________
 * <p>
 *  Copyright 2025 Adobe
 *  All Rights Reserved.
 * <p>
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * using custom templates. Generator configuration can be found in the /generator directory.
 * <p>
 * Do not edit this file manually!
 **************************************************************************/

package com.adobe.aco.model;

import com.adobe.aco.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Metadata information for a category attribute. */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.4.0")
public class FeedCategoryMetadata {
    public static final String SERIALIZED_NAME_CODE = "code";

    @SerializedName(SERIALIZED_NAME_CODE)
    private String code;

    public static final String SERIALIZED_NAME_SOURCE = "source";

    @SerializedName(SERIALIZED_NAME_SOURCE)
    private Source source;

    public static final String SERIALIZED_NAME_LABEL = "label";

    @SerializedName(SERIALIZED_NAME_LABEL)
    private String label;

    /** Data type */
    @JsonAdapter(DataTypeEnum.Adapter.class)
    public enum DataTypeEnum {
        TEXT("TEXT"),

        DECIMAL("DECIMAL"),

        INTEGER("INTEGER"),

        BOOLEAN("BOOLEAN");

        private String value;

        DataTypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static DataTypeEnum fromValue(String value) {
            for (DataTypeEnum b : DataTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<DataTypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final DataTypeEnum enumeration)
                    throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public DataTypeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return DataTypeEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            DataTypeEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_DATA_TYPE = "dataType";

    @SerializedName(SERIALIZED_NAME_DATA_TYPE)
    private DataTypeEnum dataType;

    public FeedCategoryMetadata() {}

    public FeedCategoryMetadata code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Attribute code
     *
     * @return code
     */
    @javax.annotation.Nonnull
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public FeedCategoryMetadata source(Source source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     *
     * @return source
     */
    @javax.annotation.Nonnull
    public Source getSource() {
        return source;
    }

    public void setSource(Source source) {
        this.source = source;
    }

    public FeedCategoryMetadata label(String label) {
        this.label = label;
        return this;
    }

    /**
     * Label for the attribute that is displayed in user interfaces.
     *
     * @return label
     */
    @javax.annotation.Nonnull
    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public FeedCategoryMetadata dataType(DataTypeEnum dataType) {
        this.dataType = dataType;
        return this;
    }

    /**
     * Data type
     *
     * @return dataType
     */
    @javax.annotation.Nonnull
    public DataTypeEnum getDataType() {
        return dataType;
    }

    public void setDataType(DataTypeEnum dataType) {
        this.dataType = dataType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FeedCategoryMetadata feedCategoryMetadata = (FeedCategoryMetadata) o;
        return Objects.equals(this.code, feedCategoryMetadata.code)
                && Objects.equals(this.source, feedCategoryMetadata.source)
                && Objects.equals(this.label, feedCategoryMetadata.label)
                && Objects.equals(this.dataType, feedCategoryMetadata.dataType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, source, label, dataType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FeedCategoryMetadata {\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("code");
        openapiFields.add("source");
        openapiFields.add("label");
        openapiFields.add("dataType");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("code");
        openapiRequiredFields.add("source");
        openapiRequiredFields.add("label");
        openapiRequiredFields.add("dataType");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to FeedCategoryMetadata
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!FeedCategoryMetadata.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in FeedCategoryMetadata is not found in the empty JSON string",
                                FeedCategoryMetadata.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!FeedCategoryMetadata.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `FeedCategoryMetadata` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : FeedCategoryMetadata.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("code").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `code` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("code").toString()));
        }
        // validate the required field `source`
        Source.validateJsonElement(jsonObj.get("source"));
        if (!jsonObj.get("label").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `label` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("label").toString()));
        }
        if (!jsonObj.get("dataType").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `dataType` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("dataType").toString()));
        }
        // validate the required field `dataType`
        DataTypeEnum.validateJsonElement(jsonObj.get("dataType"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!FeedCategoryMetadata.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'FeedCategoryMetadata' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<FeedCategoryMetadata> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(FeedCategoryMetadata.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<FeedCategoryMetadata>() {
                        @Override
                        public void write(JsonWriter out, FeedCategoryMetadata value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public FeedCategoryMetadata read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of FeedCategoryMetadata given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of FeedCategoryMetadata
     * @throws IOException if the JSON string is invalid with respect to FeedCategoryMetadata
     */
    public static FeedCategoryMetadata fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, FeedCategoryMetadata.class);
    }

    /**
     * Convert an instance of FeedCategoryMetadata to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
