/*************************************************************************
 * ADOBE CONFIDENTIAL
 * ___________________
 * <p>
 *  Copyright 2025 Adobe
 *  All Rights Reserved.
 * <p>
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * using custom templates. Generator configuration can be found in the /generator directory.
 * <p>
 * Do not edit this file manually!
 **************************************************************************/

package com.adobe.aco.model;

import com.adobe.aco.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Identifies the source context for a product layer, combining locale and layer name to create a
 * unique layer identifier. This allows for precise targeting of content overrides.
 */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.4.0")
public class SourceLayer {
    public static final String SERIALIZED_NAME_LOCALE = "locale";

    @SerializedName(SERIALIZED_NAME_LOCALE)
    private String locale;

    public static final String SERIALIZED_NAME_LAYER = "layer";

    @SerializedName(SERIALIZED_NAME_LAYER)
    private String layer;

    public SourceLayer() {}

    public SourceLayer locale(String locale) {
        this.locale = locale;
        return this;
    }

    /**
     * ISO locale code (for example, \&quot;en-US\&quot;, \&quot;fr-FR\&quot;, \&quot;de-DE\&quot;)
     * that specifies the target market or language. When omitted, the layer applies globally across
     * all locales. Use for market-specific customizations.
     *
     * @return locale
     */
    @javax.annotation.Nullable
    public String getLocale() {
        return locale;
    }

    public void setLocale(String locale) {
        this.locale = locale;
    }

    public SourceLayer layer(String layer) {
        this.layer = layer;
        return this;
    }

    /**
     * Unique identifier for the layer within the product&#39;s layer hierarchy. Use descriptive
     * names that indicate the layer&#39;s purpose (for example, \&quot;seasonal-winter-2024\&quot;,
     * \&quot;promotional-black-friday\&quot;, \&quot;a-b-test-variant\&quot;).
     *
     * @return layer
     */
    @javax.annotation.Nonnull
    public String getLayer() {
        return layer;
    }

    public void setLayer(String layer) {
        this.layer = layer;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourceLayer sourceLayer = (SourceLayer) o;
        return Objects.equals(this.locale, sourceLayer.locale)
                && Objects.equals(this.layer, sourceLayer.layer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(locale, layer);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SourceLayer {\n");
        sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
        sb.append("    layer: ").append(toIndentedString(layer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("locale");
        openapiFields.add("layer");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("layer");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to SourceLayer
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!SourceLayer.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in SourceLayer is not found in the empty JSON string",
                                SourceLayer.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!SourceLayer.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the `SourceLayer` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : SourceLayer.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("locale") != null && !jsonObj.get("locale").isJsonNull())
                && !jsonObj.get("locale").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `locale` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("locale").toString()));
        }
        if (!jsonObj.get("layer").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `layer` to be a primitive type in the JSON string but got `%s`",
                            jsonObj.get("layer").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!SourceLayer.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'SourceLayer' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SourceLayer> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(SourceLayer.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<SourceLayer>() {
                        @Override
                        public void write(JsonWriter out, SourceLayer value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public SourceLayer read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of SourceLayer given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of SourceLayer
     * @throws IOException if the JSON string is invalid with respect to SourceLayer
     */
    public static SourceLayer fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, SourceLayer.class);
    }

    /**
     * Convert an instance of SourceLayer to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
