/*************************************************************************
 * ADOBE CONFIDENTIAL
 * ___________________
 * <p>
 *  Copyright 2025 Adobe
 *  All Rights Reserved.
 * <p>
 * NOTICE:  All information contained herein is, and remains
 * the property of Adobe and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Adobe
 * and its suppliers and are protected by all applicable intellectual
 * property laws, including trade secret and copyright laws.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Adobe.
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * using custom templates. Generator configuration can be found in the /generator directory.
 * <p>
 * Do not edit this file manually!
 **************************************************************************/

package com.adobe.aco.client;

import com.adobe.aco.auth.AuthService;
import com.adobe.aco.auth.AuthServiceFactory;
import com.adobe.aco.http.CommerceHttpClient;
import com.adobe.aco.http.CommerceHttpClientFactory;
import com.adobe.aco.model.ClientConfig;

public class ClientBuilder {

    public static Client createClient(ClientConfig config) {
        AuthService auth =
                AuthServiceFactory.createAuthService(
                        config.getCredentials(), System.getenv("IMS_BASE_URL_OVERRIDE"));

        CommerceHttpClient http =
                CommerceHttpClientFactory.createHttpClient(
                        auth,
                        config.getTenantId(),
                        config.getRegion(),
                        config.getEnvironment(),
                        System.getenv("BASE_URL_OVERRIDE"));

        return new ClientImpl(http);
    }
}
