name: Release SDK

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'If true, simulate the commands without executing them'
        required: false
        default: 'true'

jobs:
  read-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Extract version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Show extracted version
        run: echo "Current version is ${{ steps.get_version.outputs.version }}"

      - name: Extract release version
        id: extract_version
        run: |
          RAW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          RELEASE_VERSION=${RAW_VERSION/-SNAPSHOT/}
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          echo "release-version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      - name: Sign artifacts (always runs)
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "Running: mvn verify -Psign-artifacts"
          mvn verify -Psign-release
